### ISSUE TITLE
Meteor 6.5.0 breaks email verification

### ISSUE THREAD

**Issue by mrmowgli** [erobit/meteor-accounts-ui-bootstrap-dropdown#21] opened 2013-08-23 07:11 UTC
Turned off 'insecure', now I get the following error in the console, and login won't work.  I suspect this is either a dependency or namespace issue.  Turning insecure back on doesn't seem to bring it back.

Uncaught TypeError: Cannot call method 'validateEmail' of undefined login_buttons_dropdown.js:357
login login_buttons_dropdown.js:357
loginOrSignup login_buttons_dropdown.js:338
Template._loginButtonsLoggedOutDropdown.events.click #login-buttons-password login_buttons_dropdown.js:66
(anonymous function) deftemplate.js:160
range.handler spark.js:837
(anonymous function) spark.js:734
_.each._.forEach underscore.js:79
(anonymous function) spark.js:733
(anonymous function) listener.js:108
_.each._.forEach underscore.js:79
deliver listener.js:102
_.extend.handler

**Comment by mrmowgli** [comment] 2013-08-23 08:10
Removing this package via:

```
mrt remove meteor-accounts-ui-bootstrap-dropdown
```

and  actually removing the package, deleting the package from meteorite in the ./meteorite folder 
and turning insecure back on will get fix this.  Meteorite will re-download the file and it should work correctly.

Turning insecure back on apparently leaves cached build files in the project/.meteor/build directories, so manual removal of meteor-accounts-ui-bootstrap-dropdown might be necessary to get this working again after you turn the 'insecure' package back on.

**Comment by erobit** [comment] 2013-08-23 13:07
Yes. The issue was fixed with commit/96157dc4db42406b712d32d55d70cbd594c582e0 a few days ago. Anyone who is having the problem should mrt remove / mrt add meteor-accounts-ui-bootstrap-dropdown.

I don't believe the issue is related to the insecure package though, just a namespacing issue that was missed when upgrading to feature parity with 0.6.5.

**Comment by mrmowgli** [comment] 2013-08-23 20:25
Excellent, thanks for the fix :)

**Closed as completed** 2013-08-30 00:53 UTC
